# Generated by Django 6.0.3 on 2026-03-31 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='departments',
            new_name='Department',
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_spec', models.CharField(max_length=255)),
                ('doc_image', models.ImageField(upload_to='doctor')),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.department')),
            ],
        ),
        migrations.DeleteModel(
            name='doctors',
        ),
    ]
