# Generated by Django 6.0.3 on 2026-03-31 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_departments_department_doctor_delete_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_phone', models.CharField(max_length=255)),
                ('p_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.doctor')),
            ],
        ),
    ]
